---
# development:
#   cloud_name: lorenzocloudinary
#   api_key: '486865665656777'
#   api_secret: j05QhesrqbQWDwjqKXmbGRx5FU8
#   enhance_image_tag: true
#   static_image_support: false
production:
  cloud_name: lorenzocloudinary
  api_key: '486865665656777'
  api_secret: j05QhesrqbQWDwjqKXmbGRx5FU8
  enhance_image_tag: true
  static_image_support: true
# test:
#   cloud_name: lorenzocloudinary
#   api_key: '486865665656777'
#   api_secret: j05QhesrqbQWDwjqKXmbGRx5FU8
#   enhance_image_tag: true
#   static_image_support: false
